### ISSUE TITLE
possible memory leak

### ISSUE THREAD

**Issue by deli73** [LazuriteMC/Polaroid#1]
need to do more testing, but with sufficient distinct polaroid photos rendering at once in item frames, the client can quickly run out of memory. nearly crashed my whole computer, oops

**Comment by AurySystem** [comment]
Taking lots of photos and placing them in item frames cuases a memory leak in the JRE.
Effectively more and more memory is allocated to the JDK when you take photo's but the internal minecraft memory cache seems fine.
Possibly some object doesn't get garbage collected correctly?
![image](https://user-images.githubusercontent.com/22009843/203186235-8a9b34b3-0a27-490e-8321-a8af1195ba49.png)
![2022-11-21_19 38 26](https://user-images.githubusercontent.com/22009843/203186380-dac74f3d-7818-4bbf-8820-e3964d96a3a7.png)
